### PR TITLE
Close #111. Redesigned the talk schedule grid to be a little more user-friendly

### LINKED ISSUE #111: Talk schedule page is a little confusing
* stack the days: day 1 on top, day 2 in the middle, day 3 on the bottom
* each talk slot spanning the full width and split in half
* if bored, also add a paginated version so I won't have to scroll forever on my phone on day 3

### PR DESCRIPTION
**Pull request by fcurella**
screen shot 2015-07-29 at 3 55 39 pm

### CODE REVIEW

**Comment by jefftriplett** [comment]
Are you still concerned about the "Room A" and "Room B" jumping from side to side?

**Comment by fcurella** [comment]
I am, but that's not really trivial to solve because any single slot can
have multiple rooms.

**Comment by craigbruce** [comment]
Just an FYI our schedule from Guidebook will be available via browser as well, see the PyCon 2015 guide: https://guidebook.com/guide/31995/

**Comment by jefftriplett** [comment]
Merging to develop to try but I want to hold off merging into master. I don't want people to be doublely confused because rooms jump from left side to right side.

**Pull request merged**
