### PR TITLE
One page

### PR DESCRIPTION
**Pull request by kcunning**
Pulled out a ton of design elements to make a one-page website.

### CODE REVIEW

**Comment by juliasolorzano** [comment]
@kcunning looks good! :+1: 

@jefftriplett can you verify the dates? We had talked about those before in a previous meeting and would be nice to have some official dates on here too.

**Comment by jefftriplett** [comment]
I will double check with Andrew but I have one contract in hand that looks good. All of our quotes are for September 7th so I would use the following dates: https://github.com/djangocon/djangocon-us-docs/wiki - 

Does that cover all of your dates or do we need something else? I noticed that registration date was listed and since we are using Eventbrite we are flexible on when we open it up. I was thinking by the end of January but in theory we can have it up when the splash page is up. Thoughts?

**Comment by jefftriplett** [comment]
:+1: @kcunning - great job!

**Comment by kcunning** [comment]
Julia: For some reason I can only see your full comment in my email. Yes! Please submit any changes you have!

**Pull request merged**
